INSERT INTO [ChangeLogValues]
           ([ChangeId]
           ,[FieldName]
           ,[FieldType]
           ,[NewIntValue]
           ,[NewRealValue]
           ,[NewStringValue]
           ,[NewDateValue]
           ,[NewObjectValue]
           ,[OldIntValue]
           ,[OldRealValue]
           ,[OldStringValue]
           ,[OldDateValue]
           ,[OldObjectValue])
     VALUES
           (?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?)