/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFReportParametersDialog.java
 *
 * Created on 13.1.2012, 15:36:08
 */
package com.openitech.db.components.dogodki;

import com.openitech.db.model.DbDataSource;
import com.openitech.db.model.factory.DataSourceFactory;
import com.openitech.support.Result;
import com.openitech.support.ResultProcessor;

/**
 *
 * @author domenbasic
 */
public class JFReportParametersDialog extends javax.swing.JFrame {

  private final DataSourceFactory factory;
  private ResultProcessor resultProcessor;
  private DbDataSource dataSource;

  /** Creates new form JFReportParametersDialog */
  public JFReportParametersDialog(DataSourceFactory factory) {
    this.factory = factory;
    this.dataSource = factory.getDataSource();
    this.dataSource.setAutoReload(false);
    
    initComponents();

    this.jpFilterPanel.add(factory.getFilterPanel());


  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jpFilterPanel = new javax.swing.JPanel();
    jpButtons = new javax.swing.JPanel();
    jbPotrdi = new com.openitech.db.components.JDbControlButton();
    jbPreklici = new com.openitech.db.components.JDbControlButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new java.awt.GridBagLayout());
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    getContentPane().add(jpFilterPanel, gridBagConstraints);

    jpButtons.setLayout(new java.awt.GridBagLayout());

    jbPotrdi.setOperation(com.openitech.db.components.JDbControlButton.Operation.CONFIRM);
    jbPotrdi.setText("Potrdi");
    jbPotrdi.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jbPotrdiActionPerformed(evt);
      }
    });
    jpButtons.add(jbPotrdi, new java.awt.GridBagConstraints());

    jbPreklici.setOperation(com.openitech.db.components.JDbControlButton.Operation.CANCEL);
    jbPreklici.setText("Preklièi");
    jbPreklici.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jbPrekliciActionPerformed(evt);
      }
    });
    jpButtons.add(jbPreklici, new java.awt.GridBagConstraints());

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    getContentPane().add(jpButtons, gridBagConstraints);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jbPotrdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPotrdiActionPerformed
    //
    dataSource.reload(false);
    if(resultProcessor != null){
      resultProcessor.process(new Result("OK", "Proccess parameters...", Result.OK));
    }
    setVisible(false);
    //
  }//GEN-LAST:event_jbPotrdiActionPerformed

  private void jbPrekliciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrekliciActionPerformed
    //
    if(resultProcessor != null){
      resultProcessor.process(new Result("Cancel", "Cancel", Result.CANCEL));
    }
    setVisible(false);
    //
  }//GEN-LAST:event_jbPrekliciActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private com.openitech.db.components.JDbControlButton jbPotrdi;
  private com.openitech.db.components.JDbControlButton jbPreklici;
  private javax.swing.JPanel jpButtons;
  private javax.swing.JPanel jpFilterPanel;
  // End of variables declaration//GEN-END:variables

  public void setResultProcessor(ResultProcessor resultProcessor) {
    this.resultProcessor = resultProcessor;
  }


}
