/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JdSupport.java
 *
 * Created on 30.11.2011, 23:48:34
 */

package com.openitech.support;

/**
 *
 * @author domenbasic
 */
public class JdSupport extends javax.swing.JDialog {

  private ResultProcessor resultProcessor;

    /** Creates new form JdSupport */
    public JdSupport(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

  public void setResultProcessor(ResultProcessor resultProcessor) {
    this.resultProcessor = resultProcessor;
  }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jLabel2 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jtfOpis = new com.openitech.db.components.JDbTextArea();
    jPanel1 = new javax.swing.JPanel();
    jbPotrdi = new com.openitech.db.components.JDbControlButton();
    jbPreklici = new com.openitech.db.components.JDbControlButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    getContentPane().setLayout(new java.awt.GridBagLayout());

    jLabel2.setText("Opis napake");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    getContentPane().add(jLabel2, gridBagConstraints);

    jtfOpis.setColumns(20);
    jtfOpis.setRows(15);
    jScrollPane1.setViewportView(jtfOpis);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    getContentPane().add(jScrollPane1, gridBagConstraints);

    jPanel1.setLayout(new java.awt.GridBagLayout());

    jbPotrdi.setOperation(com.openitech.db.components.JDbControlButton.Operation.CONFIRM);
    jbPotrdi.setText("Pošlji");
    jbPotrdi.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jbPotrdiActionPerformed(evt);
      }
    });
    jPanel1.add(jbPotrdi, new java.awt.GridBagConstraints());

    jbPreklici.setOperation(com.openitech.db.components.JDbControlButton.Operation.CANCEL);
    jbPreklici.setText("Preklièi");
    jbPreklici.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jbPrekliciActionPerformed(evt);
      }
    });
    jPanel1.add(jbPreklici, new java.awt.GridBagConstraints());

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    getContentPane().add(jPanel1, gridBagConstraints);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jbPotrdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPotrdiActionPerformed
      //
      if(resultProcessor != null){
        resultProcessor.process(new Result("Napaka", jtfOpis.getText(), Result.OK));
      }
      setVisible(false);
      //
    }//GEN-LAST:event_jbPotrdiActionPerformed

    private void jbPrekliciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrekliciActionPerformed
      //
      if(resultProcessor != null){
        resultProcessor.process(new Result(null, null, Result.CANCEL));
      }
      setVisible(false);
      //
    }//GEN-LAST:event_jbPrekliciActionPerformed

   

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private com.openitech.db.components.JDbControlButton jbPotrdi;
  private com.openitech.db.components.JDbControlButton jbPreklici;
  private com.openitech.db.components.JDbTextArea jtfOpis;
  // End of variables declaration//GEN-END:variables

}
