SELECT [Id]
      ,[PropertyType]
      ,[PropertyName]
      ,[FieldType]
      ,CASE WHEN [FieldType] = 1 THEN [IntValue]
            WHEN [FieldType] = 2 THEN [RealValue]
            WHEN [FieldType] = 3 THEN [StringValue]
            WHEN [FieldType] = 4 THEN [DateValue]
            WHEN [FieldType] = 5 THEN [ObjectValue]
            WHEN [FieldType] = 6 THEN [ClobValue]
            ELSE CAST((null) AS VARCHAR)
       END AS [PropertyValue]
  FROM <%ChangeLog%>.[dbo].[NamedPropertyValues]
LEFT OUTER JOIN <%ChangeLog%>.[dbo].[VariousValues]
  ON [VariousValues].[Id] = [NamedPropertyValues].[ValueId]
WHERE [PropertyType] = ? AND [PropertyName] = ?