SELECT TOP 1
       [ID_PP]
      ,[ID_KONTAKTA]
      ,(SELECT [ELEKTRONSKA_POSTA] FROM [ChangeLog].[dbo].[E_244_KEML01_valid] E244 WITH  (NOLOCK, NOEXPAND)
      WHERE E244.ID_KONTAKTA = E202.ID_KONTAKTA) AS [ELEKTRONSKA_POSTA]
      
  FROM [ChangeLog].[dbo].[E_202_RPPK03_valid] E202 WITH (NOLOCK, NOEXPAND)
  WHERE ID_PP = ?


