SELECT TOP 1
       [ID_PP]
      ,[ID_KONTAKTA]
      ,(SELECT [TELEFON_OS] FROM [ChangeLog].[dbo].[E_243_KTEL01_valid] E243 WITH  (NOLOCK, NOEXPAND)
      WHERE E243.ID_KONTAKTA = E195.ID_KONTAKTA) AS TELEFON_OS
      ,(SELECT [TELEFON_STEVILKA] FROM [ChangeLog].[dbo].[E_243_KTEL01_valid] E243 WITH  (NOLOCK, NOEXPAND)
      WHERE E243.ID_KONTAKTA = E195.ID_KONTAKTA) AS TELEFON_STEVILKA

  FROM [ChangeLog].[dbo].[E_195_RPPK01_valid] E195 WITH (NOLOCK, NOEXPAND)
  WHERE ID_PP = ?


