SELECT
      [ID_KONTAKTA]

  FROM [ChangeLog].[dbo].[E_243_KTEL01_valid] WITH (NOLOCK, NOEXPAND)
  WHERE [TELEFON_OS] = ? AND [TELEFON_STEVILKA] = ? --AND [KONTAKT_TIP_KONTAKTA] = CAST(? AS VARCHAR)


