/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DefaultFilterPanel.java
 *
 * Created on 14.10.2010, 12:09:13
 */
package com.openitech.db.filters;

import java.awt.Component;
import java.awt.Container;
import java.util.Map;
import javax.swing.text.Document;

/**
 *
 * @author domenbasic
 */
public class DefaultFilterPanel extends javax.swing.JPanel implements Cloneable {

  protected DataSourceFiltersMap filtersMap;
  private boolean addSearchButton = false;

  /**
   * Creates new form JPKadrovskaEvidencaFilterPanel
   */
  public DefaultFilterPanel(Map<String, Document> namedDocuments,
          DataSourceFiltersMap filtersMap) {
    this(namedDocuments, (JPDbDataSourceFilter) null, filtersMap);
  }

  public DefaultFilterPanel(Map<String, Document> documents, DefaultFilterPanel defaultFilterPanel, DataSourceFiltersMap filtersMap) {
    this(documents, defaultFilterPanel.getJPDbDataSourceFilter(), filtersMap);
  }

  /**
   * Creates new form JPKadrovskaEvidencaFilterPanel
   */
  public DefaultFilterPanel(Map<String, Document> namedDocuments, com.openitech.db.filters.JPDbDataSourceFilter parentFilterPanel,
          DataSourceFiltersMap filtersMap) {
    this.filtersMap = filtersMap;
    initComponents();

    dbDataSourceFilter.setNamedDocuments(namedDocuments);
    dbDataSourceFilter.setParentFilterPanel(parentFilterPanel);
    dbDataSourceFilter.getFilters().putAll(filtersMap);

    for (DataSourceFilters dataSourceFilters : dbDataSourceFilter.getFilters().keySet()) {
      addSearchButton = addSearchButton || dataSourceFilters.isUseSearchButton();
    }
    invalidate();
  }

  public JPDbDataSourceFilter getJPDbDataSourceFilter() {
    return dbDataSourceFilter;
  }

  @Override
  public void setEnabled(boolean enabled) {
    setEnabled(this, enabled);
  }

  private void setEnabled(Container container, boolean enabled) {
    if (this.equals(container)) {
      super.setEnabled(enabled);
    } else {
      container.setEnabled(enabled);
    }
    for (Component component : container.getComponents()) {
      component.setEnabled(enabled);
      if (component instanceof Container) {
        setEnabled((Container) component, enabled);
      }
    }
  }

  @Override
  public Object clone() {
    return new DefaultFilterPanel(dbDataSourceFilter.getNamedDocuments(), dbDataSourceFilter, filtersMap);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    dbDataSourceFilter = new com.openitech.db.filters.JPDbDataSourceFilter();
    jbIsci = new javax.swing.JButton();

    setBorder(javax.swing.BorderFactory.createTitledBorder("Filter"));
    setLayout(new java.awt.GridBagLayout());
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    add(dbDataSourceFilter, gridBagConstraints);

    jbIsci.setText("Išèi");
    jbIsci.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jbIsciActionPerformed(evt);
      }
    });
    if(addSearchButton){
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
      add(jbIsci, gridBagConstraints);
    }
  }// </editor-fold>//GEN-END:initComponents

  private void jbIsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIsciActionPerformed
    // TODO add your handling code here:
    FilterManager.getInstance().doSeek();
  }//GEN-LAST:event_jbIsciActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private com.openitech.db.filters.JPDbDataSourceFilter dbDataSourceFilter;
  private javax.swing.JButton jbIsci;
  // End of variables declaration//GEN-END:variables
}
