/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DefaultFilterPanel.java
 *
 * Created on 14.10.2010, 12:09:13
 */
package com.openitech.db.filters;

import java.util.Map;
import javax.swing.text.Document;

/**
 *
 * @author domenbasic
 */
public class DefaultFilterPanel extends javax.swing.JPanel implements Cloneable {

  protected DataSourceFiltersMap filtersMap;

  /**
   * Creates new form JPKadrovskaEvidencaFilterPanel
   */
  public DefaultFilterPanel(Map<String, Document> namedDocuments,
          DataSourceFiltersMap filtersMap) {
    this(namedDocuments, null, filtersMap);
  }
  
  /**
   * Creates new form JPKadrovskaEvidencaFilterPanel
   */
  public DefaultFilterPanel(Map<String, Document> namedDocuments, com.openitech.db.filters.JPDbDataSourceFilter parentFilterPanel,
          DataSourceFiltersMap filtersMap) {
    this.filtersMap = filtersMap;
    initComponents();

    jPDbDataSourceFilter1.setNamedDocuments(namedDocuments);
    jPDbDataSourceFilter1.setParentFilterPanel(parentFilterPanel);
    jPDbDataSourceFilter1.getFilters().putAll(filtersMap);
  }

  @Override
  public Object clone() {
    return new DefaultFilterPanel(jPDbDataSourceFilter1.getNamedDocuments(), jPDbDataSourceFilter1, filtersMap);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jPDbDataSourceFilter1 = new com.openitech.db.filters.JPDbDataSourceFilter();

    setLayout(new java.awt.GridBagLayout());
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    add(jPDbDataSourceFilter1, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private com.openitech.db.filters.JPDbDataSourceFilter jPDbDataSourceFilter1;
  // End of variables declaration//GEN-END:variables
}
