/****** Script for SelectTopNRows command from SSMS  ******/
SELECT [object_id]
      ,[name]
      ,[column_id]
      ,[system_type_id]
      ,[user_type_id]
      ,[max_length]
      ,[precision]
      ,[scale]
      ,[collation_name]
      ,[is_nullable]
      ,[is_ansi_padded]
      ,[is_rowguidcol]
      ,[is_identity]
      ,[is_computed]
      ,[is_filestream]
      ,[is_replicated]
      ,[is_non_sql_subscribed]
      ,[is_merge_published]
      ,[is_dts_replicated]
      ,[is_xml_document]
      ,[xml_collection_id]
      ,[default_object_id]
      ,[rule_object_id]
      ,[is_sparse]
      ,[is_column_set]
  FROM [ChangeLog].[sys].[columns]
  WHERE object_id = OBJECT_ID(?)
		AND column_id > (SELECT COUNT(*) FROM <%ChangeLog%>.[sys].[columns] WHERE object_id = OBJECT_ID(N'<%ChangeLog%>.[dbo].[Events]'))