INSERT INTO #T_EVENT_VALUES
           ([EventId]
           ,[IdPolja]
           ,[FieldValueIndex]
           ,[ValueId]
           ,[FieldType]
           ,[IntValue]
           ,[RealValue]
           ,[StringValue]
           ,[DateValue]
           ,[ObjectValue]
           ,[ClobValue])
     VALUES
           (?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?
           ,?)