/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImageTest2.java
 *
 * Created on 28.2.2011, 17:20:34
 */

package com.openitech.db.components;

/**
 *
 * @author domenbasic
 */
public class ImageTest2 extends javax.swing.JFrame {

    /** Creates new form ImageTest2 */
    public ImageTest2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jPanel1 = new javax.swing.JPanel();
    jPanel2 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jDbJXImagePanel1 = new com.openitech.db.components.JDbJXImagePanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setLayout(new java.awt.GridBagLayout());

    jLabel1.setText("jLabel1");
    jPanel2.add(jLabel1);

    jLabel2.setText("jLabel2");
    jPanel2.add(jLabel2);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    jPanel1.add(jPanel2, gridBagConstraints);

    javax.swing.GroupLayout jDbJXImagePanel1Layout = new javax.swing.GroupLayout(jDbJXImagePanel1);
    jDbJXImagePanel1.setLayout(jDbJXImagePanel1Layout);
    jDbJXImagePanel1Layout.setHorizontalGroup(
      jDbJXImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    jDbJXImagePanel1Layout.setVerticalGroup(
      jDbJXImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 276, Short.MAX_VALUE)
    );

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    jPanel1.add(jDbJXImagePanel1, gridBagConstraints);

    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImageTest2().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private com.openitech.db.components.JDbJXImagePanel jDbJXImagePanel1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  // End of variables declaration//GEN-END:variables

}
