/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ImageTest.java
 *
 * Created on 28.2.2011, 17:17:38
 */

package com.openitech.db.components;

/**
 *
 * @author domenbasic
 */
public class ImageTest extends javax.swing.JPanel {

    /** Creates new form ImageTest */
    public ImageTest() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jDbJXImagePanel1 = new com.openitech.db.components.JDbJXImagePanel();

    setLayout(new java.awt.GridBagLayout());

    javax.swing.GroupLayout jDbJXImagePanel1Layout = new javax.swing.GroupLayout(jDbJXImagePanel1);
    jDbJXImagePanel1.setLayout(jDbJXImagePanel1Layout);
    jDbJXImagePanel1Layout.setHorizontalGroup(
      jDbJXImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    jDbJXImagePanel1Layout.setVerticalGroup(
      jDbJXImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    add(jDbJXImagePanel1, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private com.openitech.db.components.JDbJXImagePanel jDbJXImagePanel1;
  // End of variables declaration//GEN-END:variables

}
