/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PKToString.java
 *
 * Created on 2.11.2010, 13:41:13
 */
package com.openitech.primarkey;

import com.openitech.value.VariousValue;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author domenbasic
 */
public class PKToString extends javax.swing.JFrame {

  /** Creates new form PKToString */
  public PKToString() {
    initComponents();
    DbConnection.register();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jPanel1 = new javax.swing.JPanel();
    jDbTextField1 = new com.openitech.db.components.JDbTextField();
    jButton1 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setLayout(new java.awt.GridBagLayout());

    jDbTextField1.setColumns(20);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    jPanel1.add(jDbTextField1, gridBagConstraints);

    jButton1.setText("Izpisi");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    jPanel1.add(jButton1, new java.awt.GridBagConstraints());

    getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

      String text = jDbTextField1.getText();
//      Pattern pattern = Pattern.compile("\\p{Punct}*\\p{Punct}");
//      Matcher matcher = pattern.matcher(text);
//      if(matcher.matches()){
//        for (int i = 0; i < matcher.groupCount(); i++) {
//        String group = matcher.group(i);
//        System.out.println(group);
//        }
//      }
      int start = 0;
      int end = 0;
      StringBuilder stringBuilder = new StringBuilder(text);
      for (int i = 0; i < stringBuilder.length(); i++) {
        char crka = stringBuilder.charAt(i);
        if (crka == '{') {
          start = i;
        }
        if (crka == '}') {
        try {
          end = i;
          String tekstVOklepajih = stringBuilder.substring(start + 1, end);
          String[] split = tekstVOklepajih.split(";");
          for (String string : split) {
            int vrednost = Integer.parseInt(string, 16);
            System.out.print(vrednost + " ; ");
          }
          System.out.print(VariousValue.newVariousValue(Integer.parseInt(split[split.length - 1], 16)).getValue());
          System.out.println();
        } catch (SQLException ex) {
          Logger.getLogger(PKToString.class.getName()).log(Level.SEVERE, null, ex);
        }
        }

      }
//

    }//GEN-LAST:event_jButton1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new PKToString().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private com.openitech.db.components.JDbTextField jDbTextField1;
  private javax.swing.JPanel jPanel1;
  // End of variables declaration//GEN-END:variables
}
