/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDIzbiraNaslova.java
 *
 * Created on 13.11.2008, 12:53:00
 */
package com.openitech.db.components.test;

/**
 *
 * @author uros
 */
public class JDIzbiraNaslova extends javax.swing.JDialog {

  /** Creates new form JDIzbiraNaslova */
  public JDIzbiraNaslova(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    dbDataSource1 = DbDataModel.getInstance().dsKadrovskaEvidenca;
    try {
      jPIzbiraNaslova1 = new com.openitech.db.components.JPIzbiraNaslova();
    } catch (java.sql.SQLException e1) {
      e1.printStackTrace();
    }
    jButton1 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jPIzbiraNaslova1.setCnHisnaStevilka("hs_hd_SN");
    jPIzbiraNaslova1.setCnHisnaStevilkaMID("hs_mid_SN");
    jPIzbiraNaslova1.setCnNaselje("na_uime_SN");
    jPIzbiraNaslova1.setCnNaseljeMID("na_mid_SN");
    jPIzbiraNaslova1.setcnPosta("pt_uime_SN");
    jPIzbiraNaslova1.setcnPostnaStevilka("pt_id_SN");
    jPIzbiraNaslova1.setcnPostnaStevilkaMID("pt_mid_SN");
    jPIzbiraNaslova1.setCnUlica("ul_uime_SN");
    jPIzbiraNaslova1.setCnUlicaMID("ul_mid_SN");
    jPIzbiraNaslova1.setDataSource(dbDataSource1);

    jButton1.setText("jButton1");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(311, Short.MAX_VALUE)
        .addComponent(jButton1)
        .addGap(183, 183, 183))
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addGap(0, 0, Short.MAX_VALUE)
          .addComponent(jPIzbiraNaslova1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(0, 0, Short.MAX_VALUE)))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(161, Short.MAX_VALUE)
        .addComponent(jButton1)
        .addGap(29, 29, 29))
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addGap(0, 76, Short.MAX_VALUE)
          .addComponent(jPIzbiraNaslova1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGap(0, 77, Short.MAX_VALUE)))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    jPIzbiraNaslova1.clear();
  }//GEN-LAST:event_jButton1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    DbConnection.register();

    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        initDbModel();
        if (DbDataModel.getInstance().getDbConnection() != null) {

          JDIzbiraNaslova dialog = new JDIzbiraNaslova(new javax.swing.JFrame(), true);
          dialog.addWindowListener(new java.awt.event.WindowAdapter() {

            public void windowClosing(java.awt.event.WindowEvent e) {
              System.exit(0);
            }
          });
          dialog.setVisible(true);
        }
        if (DbDataModel.getInstance().getDbConnection() == null) {
          System.exit(0);
        }
      }

      private void initDbModel() {
        DbDataModel.getInstance();
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private com.openitech.db.model.DbDataSource dbDataSource1;
  private javax.swing.JButton jButton1;
  private com.openitech.db.components.JPIzbiraNaslova jPIzbiraNaslova1;
  // End of variables declaration//GEN-END:variables
}
