/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDbFilePanel.java
 *
 * Created on 23.10.2011, 19:38:38
 */
package com.openitech.db.components;

import com.openitech.db.model.DbDataSource;
import java.awt.Desktop;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author domenbasic
 */
public class JDbFilePanel extends javax.swing.JPanel {

  private final DbDataSource dataSource;
  private final String columnName;

  /** Creates new form JDbFilePanel */
  public JDbFilePanel(DbDataSource dataSource, String columnName) {
    this.dataSource = dataSource;
    this.columnName = columnName;
    initComponents();

    jtfFileName.setColumnName(columnName + "FileName");
    jtfFileName.setDataSource(dataSource);
  }

  public void setColumnLength(Integer columnLength) {
    jtfFileName.setColumns(columnLength);
  }
  private boolean ignoreSelectAll = false;

  /**
   * Get the value of ignoreSelectAll
   *
   * @return the value of ignoreSelectAll
   */
  public boolean isIgnoreSelectAll() {
    return ignoreSelectAll;
  }

  /**
   * Set the value of ignoreSelectAll
   *
   * @param ignoreSelectAll new value of ignoreSelectAll
   */
  public void setIgnoreSelectAll(boolean ignoreSelectAll) {
    this.ignoreSelectAll = ignoreSelectAll;
    jtfFileName.setIgnoreSelectAll(ignoreSelectAll);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    fc = new javax.swing.JFileChooser();
    jtfFileName = new com.openitech.db.components.JDbTextField();
    jbChoose = new javax.swing.JButton();
    jbOpen = new javax.swing.JButton();

    setLayout(new java.awt.GridBagLayout());

    jtfFileName.setColumns(20);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.weightx = 0.5;
    add(jtfFileName, gridBagConstraints);

    jbChoose.setText("Choose");
    jbChoose.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jbChooseActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    add(jbChoose, gridBagConstraints);

    jbOpen.setText("Open");
    jbOpen.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jbOpenActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.weightx = 1.0;
    add(jbOpen, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

    private void jbOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOpenActionPerformed
      //
      FileOutputStream fo = null;
      try {
        String storedFileName = dataSource.getString(columnName + "FileName");
        if (storedFileName != null) {
          byte[] bytes = dataSource.getBytes(columnName);
          if (bytes != null) {
            String filename = System.getProperty("java.io.tmpdir") + System.getProperty("file.separator") + Calendar.getInstance().getTimeInMillis() + "_" + storedFileName;
            java.io.File file = new java.io.File(filename);
//                  if (!System.getProperty("os.name").equals("Linux")) {
//                    file.deleteOnExit();
//                  }
            fo = new FileOutputStream(file);
            fo.write(bytes);
            fo.close();

            if (file.exists()) {
              if (Desktop.getDesktop().isSupported(Desktop.Action.OPEN)) {
                Desktop.getDesktop().open(file);
              }
            }
          }
        }
      } catch (Exception ex) {
        Logger.getLogger(Logger.GLOBAL_LOGGER_NAME).log(Level.SEVERE, null, ex);
      }

      //
    }//GEN-LAST:event_jbOpenActionPerformed

    private void jbChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbChooseActionPerformed
      //
      int returnVal = fc.showOpenDialog(null);
      if (returnVal == JFileChooser.APPROVE_OPTION) {
        File openFile = fc.getSelectedFile();
        try {
          dataSource.updateString(columnName + "FileName", openFile.getName());
          FileInputStream fi = new FileInputStream(openFile);
          byte[] bytes = new byte[(int) openFile.length()];

          fi.read(bytes);

          dataSource.updateBytes(columnName, bytes);


        } catch (Exception ex) {
          Logger.getLogger(Logger.GLOBAL_LOGGER_NAME).log(Level.SEVERE, null, ex);
        }
      }
      //
    }//GEN-LAST:event_jbChooseActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JFileChooser fc;
  private javax.swing.JButton jbChoose;
  private javax.swing.JButton jbOpen;
  private com.openitech.db.components.JDbTextField jtfFileName;
  // End of variables declaration//GEN-END:variables
}
